export const allProjects = [
  // {
  //   title: "ILTP Website",
  //   description: `Ever heard of the International Leadership Training Program (ILTP)? Well, I built their website using ReactJS! It's this cool volunteer organization based in the US. Here's the kicker: I tackled the whole website backend myself, since I was still learning about Headless CMS. That was quite the adventure, let me tell you. But hey, the result? A snazzy website that showcases my problem-solving skills, adaptability, and commitment to creating awesome user experiences.`,
  //   tags: ["ReactJS", "Bootstrap", "Firebase", "PayPal Integration"],
  //   imagePath: "/iltp-preview.jpg",
  //   projectLink: "https://iltp.org/",
  //   githubLink: "https://github.com/pjguitar15/iltpwebsite",
  // },
  {
    title: "DevGuide Blog App",
    description: `DevGuide.Blog is a React based application which is one of my personal project I worked hard for. This app I built allows users two write and publish dev related content on the Internet. One of the features built on this is that, it is fully functional and dynamic. A dashboard is created to allow users configure things such as blog creation, check the analytics, and update their accounts from the settings.`,
    tags: ["ReactJS", "TailwindCSS", "TypeScript", "Firebase"],
    imagePath: "/devblog.png",
    projectLink: "https://react-blog-app-sand.vercel.app/",
    githubLink: "https://github.com/pjguitar15/react-blog-app",
  },
  {
    title: "Martial Arts Scoring System",
    description: `
I developed an app using ReactJS, TypeScript, Firebase, and TailwindCSS that facilitates the creation of games with three user roles: viewers, jury, and admin. Viewers can see scores updated in real-time, the jury can score players, and the admin has full control, including scoring, decreasing scores, updating match numbers, and managing the game timer with start, pause, and restart functions.`,
    tags: ["ReactJS", "TailwindCSS", "TypeScript", "Firebase"],
    imagePath: "/timd.png",
    projectLink: "https://timd-pointing-system.vercel.app/",
    githubLink: "https://github.com/pjguitar15/timd-pointing-system",
  },
  {
    title: "Client Wedding Gallery Website",
    description: `

I created a static wedding gallery website using React, TypeScript, and TailwindCSS. This project showcases elegant wedding photos in a responsive and visually appealing layout. Leveraging React and TypeScript ensures a dynamic and robust user experience, while TailwindCSS provides a sleek and adaptable design, making the gallery both functional and beautiful across all devices.`,
    tags: ["ReactJS", "TailwindCSS", "TypeScript"],
    imagePath: "/junmay.png",
    projectLink: "https://junmay-website.vercel.app/",
    githubLink: "https://github.com/pjguitar15/junmay-website",
  },
  {
    title: "Ingredient Savvy",
    description: `Built with NextJS, TypeScript, TailwindCSS, and a Meal API, this project is one of my personal achievements in web development. This app gives you knowledge about how to prepare a lot of different meals from all around the world. Through this project, I've demonstrated my proficiency in leveraging modern web technologies to build engaging user experiences and contribute to my growing portfolio.`,
    tags: ["NextJS", "TypeScript", "TailwindCSS", "MealAPI"],
    imagePath: "/meal-app.jpg",
    projectLink: "https://next-meal-sooty.vercel.app/search?q=chicken",
    githubLink: "https://github.com/pjguitar15/next-meal",
  },
  {
    title: "Vocab Vault",
    description: `This project represents one of my personal achievements in web development using Next.js and Tailwind CSS. Created not only for personal enjoyment but also as a means to enhance my portfolio, this Next.js application showcases my skills in crafting responsive and visually appealing web solutions. Through this project, I've demonstrated my proficiency in leveraging modern web technologies to build engaging user experiences and contribute to my growing portfolio.`,
    tags: ["NextJS", "Dictionary API", "TailwindCSS"],
    imagePath: "/vocabvault.jpg",
    projectLink: "https://next-dictionary-ashen.vercel.app/",
    githubLink: "https://github.com/pjguitar15/next-dictionary",
  },
  // {
  //   title: 'Newsletter Email Validation',
  //   description: `This is a simple project based on NextJS, TypeScript, and TailwindCSS that showcases email validation.`,
  //   tags: ['ReactJS', 'TypeScript', 'TailwindCSS'],
  //   imagePath: '/newsletter-validation.jpg',
  //   projectLink: 'https://react-newsletter-email-validation.vercel.app/',
  //   githubLink:
  //     'https://github.com/pjguitar15/react-newsletter-email-validation',
  // },
  // {
  //   title: 'Bullish Beast Website',
  //   description:
  //     'In this project, I undertook the development of a website for a client, who ultimately decided to cancel the project. This experience provided me with valuable insights into effective client communication. Regrettably, I encountered a challenging situation where I invested significant time and effort, nearly a month, building the website. The client consistently requested revisions, leading to increasing complexity in the project. Ultimately, I made the difficult decision to discontinue the project, but I emerged from this experience having gained invaluable lessons.',
  //   tags: ['ReactJS', 'Firebase'],
  //   imagePath: '/bullishbeast.jpg',
  //   projectLink: 'https://bullishbeast.netlify.app/',
  //   githubLink: 'https://github.com/pjguitar15/forex-react',
  // },
  // {
  //   title: 'AI-Powered Website',
  //   description: `Allow me to introduce one of my noteworthy client projects, a website meticulously crafted with ReactJS, Bootstrap, and Firebase. This particular creation was tailored to serve a valued client on Fiverr, with the primary objective of presenting their exceptional product to the world. Please note, however, that this website serves as a demonstration of my capabilities.`,
  //   tags: ['ReactJS', 'Bootstrap 4', 'Firebase'],
  //   imagePath: '/ai-verification.jpg',
  //   projectLink: 'https://sparkling-kitten-68894b.netlify.app/',
  //   githubLink: 'https://github.com/pjguitar15/id-verification-website-react',
  // },
  // {
  //   title: 'Guitar Shop Website',
  //   description: `This is one of my first few projects when I first started learning ReactJS. This is a very simple frontend website application that showcases nice guitars. `,
  //   tags: ['ReactJS', 'Bootstrap'],
  //   imagePath: '/guitar-shop.jpg',
  //   projectLink: 'https://philcobguitarshop.netlify.app/',
  //   githubLink: 'https://github.com/pjguitar15/react-guitar-ecommerce',
  // },
  // {
  //   title: "Movie App",
  //   description: `Here's one of my personal projects where I built a website using ReactJs and Tailwind CSS, incorporating the TMDB Movie API. This straightforward yet engaging application allows users to seamlessly retrieve data from the API, dynamically load content, and utilize a convenient search feature.`,
  //   tags: ["NextJS", "API", "Tailwindcss"],
  //   imagePath: "/movie-app.jpg",
  //   projectLink: "https://next-movie-app-kohl.vercel.app/",
  //   githubLink: "https://github.com/pjguitar15/next-movie-app",
  // },
];
